services:
  backend:
    build: ./back
    container_name: my-app-backend
    ports:
      - "5000:5000" 
    environment:
      - LLM_API_KEY=${LLM_API_KEY:-}
      - LLM_MODEL=${LLM_MODEL:-}
      - LLM_API_URL=${LLM_API_URL:-}
      - LLM_API_FOLDER=${LLM_API_FOLDER:-}
      - LLM_FOLDER_ID=${LLM_FOLDER_ID:-}
      - LLM_MAX_OUTPUT_TOKENS=${LLM_MAX_OUTPUT_TOKENS:-2000}
    restart: always

  frontend:
    build: ./frontend
    container_name: my-app-frontend
    ports:
      - "5173:5173" 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    depends_on:
      - backend
    restart: always
